apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goserver.fullname" . }}-env
data:
  NAME: {{ .Values.env.NAME | quote }}
  AGE: {{ .Values.env.AGE | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goserver.fullname" . }}-turtles
data:
  members: {{ .Values.configmap.members | quote }}
  weapons: {{ .Values.configmap.weapons | quote }}
