apiVersion: v1
kind: Service
metadata:
  name: goserver-svc
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
