apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: "interviewlgc.sandbox.letsgetchecked-dev1.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: goserver-svc
            port:
              number: 80
      - pathType: Prefix
        path: "/healthz"
        backend:
          service:
            name: goserver-svc
            port:
              number: 80
      - pathType: Prefix
        path: "/secrets"
        backend:
          service:
            name: goserver-svc
            port:
              number: 80

  tls:
  - hosts:
    - "interviewlgc.sandbox.letsgetchecked-dev1.com"
    secretName: letsencrypt-tls
