variable "project" {}
variable "cluster_name" {}
variable "cidr_block" {}
variable "retention_days" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "instance_type" {}
variable "capacity_type" {}
variable "vpc_id" {}
variable "private_subnet_ids" {}